### ISSUE TITLE
عدم نمایش SVG

### ISSUE THREAD

**Issue by cipherbullet** [peymanslh/iranmap#1]
سلام و وقت بخیر
ضمن سپاس از زحمات شما در تهیه این مورد، بعد از باز کردن فایل نقشه لود نمیشه
مشکلی در فایل svg هست یا باید اقدامی جهت نمایش انجام بشه؟

**Comment by peymanslh** [comment]
<div dir="rtl">
سلام

برای لود شدن درست باید فایل رو روی یه سرور یا لوکال هاست خودتون اجرا کنین

و یا میتونین checkout کنین به کامیت های قبلی و تست کنین
</div>
